# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# useful commands:
# pip install pre-commit
# pre-commit install
# pre-commit install --install-hooks
# pre-commit autoupdate  # to check latest hooks repos

repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--filter-files" ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          # - flake8-import-order
          # isort used instead
          - flake8-builtins
          - flake8-future-annotations
#          - flake8-docstrings>=1.6.0
          - flake8-rst-docstrings
#          # flake8-rst-docstrings dependency, leaving it here
#          # in case it requires a version pin
          - pydocstyle
          - pygments

## TODO: fix logic
#  - repo: local
#    hooks:
#      - id: bump2version
#        name: Bump2Version
#        description: Increment build number with bump2version
#        entry: bump2version
#        language: python
#        args: ['build', '--allow-dirty']
#        exclude: ''
#        always_run: true