[tool.bumpversion]
current_version = "3.5.7"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
commit = true
message = "Bump version: {current_version} → {new_version}"
tag = true
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"

[[tool.bumpversion.files]]
filename = "VERSION"

[[tool.bumpversion.files]]
filename = "lamb/__init__.py"


[tool.ruff]
target-version = "py311"
line-length = 120
exclude = [
    "playground*.ipynb",
    "tests"
]

[tool.ruff.lint]
extend-select = [
    "A",
    "FA",
    # isort
    "I",
#    # flake8-bugbear
#    "B",
#    # flake8-simplify
#    "SIM",
#    # pyupgrade
#    "UP",
]
fixable = [
    "I",
#    "UP", "SIM"
]
ignore = ["F401", "E402"]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "lamb", "first-party", "local-folder"]

[tool.ruff.lint.isort.sections]
"lamb" = ["lamb"]

[tool.ruff.format]
docstring-code-format = true
quote-style = "double"
indent-style = "space"