#-*- coding: utf-8 -*-
__author__ = 'KoNEW'

LAMB_DEVICE_INFO_HEADER_FAMILY = 'HTTP_X_LAMB_DEVICE_FAMILY'
LAMB_DEVICE_INFO_HEADER_PLATFORM = 'HTTP_X_LAMB_DEVICE_PLATFORM'
LAMB_DEVICE_INFO_HEADER_OS_VERSION = 'HTTP_X_LAMB_DEVICE_OS_VERSION'
LAMB_DEVICE_INFO_HEADER_LOCALE = 'HTTP_X_LAMB_DEVICE_LOCALE'
LAMB_DEVICE_INFO_HEADER_APP_VERSION = 'HTTP_X_LAMB_APP_VERSION'
LAMB_DEVICE_INFO_HEADER_APP_BUILD = 'HTTP_X_LAMB_APP_BUILD'

LAMB_PAGINATION_LIMIT_DEFAULT = 100
LAMB_PAGINATION_LIMIT_MAX = 5000
LAMB_PAGINATION_KEY_OFFSET = 'offset'
LAMB_PAGINATION_KEY_LIMIT = 'limit'
LAMB_PAGINATION_KEY_ITEMS = 'items'
LAMB_PAGINATION_KEY_TOTAL = 'total_count'

LAMB_SORTING_KEY = 'sorting'


LAMB_IMAGE_SIZE_THUMBNAIL = 100
LAMB_IMAGE_SIZE_SMALL = 200
LAMB_IMAGE_SIZE_MEDIUM = 400
LAMB_IMAGE_SIZE_LARGE = 800
LAMB_IMAGE_UPLOAD_QUALITY = 95
LAMB_IMAGE_UPLOAD_SERVICE = 'lamb.service.image.ImageUploadServiceDisk'
